[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["booskander"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
dash = "^2.17.1"
plotly = "^5.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
